### ISSUE TITLE
Rethink localization of strings used in LOGGER calls

### ISSUE THREAD

**Issue by kelemeng** [LibreOffice/WollMux#408]
Currently there is a lot of LOGGER calls in the code with inconsistent language: some strings are German, some are English. 
Some are marked for translation with the L.m() call, some are not.
Proposal is:
(1) Translate all such strings to English
(2) Rethink whether all these are really worth translating into all languages. Are these visible anywhere else than in the wollmux.log file?
Add/remove L.m() calls as deemed fit.

**Comment by smehrbrodt** [comment]
Yes having English strings for all LOGGER calls should be enough.
I started work here, feel free to do the rest.

`git grep LOGGER  | grep "L\.m"`
